### ISSUE TITLE
Question on an example

### ISSUE THREAD

**Issue by mkjsix** [mingfang/terraform-k8s-modules#4]
Hi,

Just out of curiosity I was looking at [this example](https://github.com/mingfang/terraform-k8s-modules/tree/master/examples/mongodb) and  I noticed you put both Eve and RESTHeart in the same deployment. I just wonder if there's any specific reason, as AFAIK the two products have a high degree of overlapping, both providing a REST API on top of MongoDB. 
Thank you.

**Comment by mingfang** [comment]
@mkjsix 
No specific reason. Just a matter of convenience both for me and for anyone wanting to compare the two.
Thanks for your time.
